// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package gonetworkmanager

import (
	"github.com/Wifx/gonetworkmanager/v2"
	"github.com/godbus/dbus/v5"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDeviceWireless creates a new instance of MockDeviceWireless. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDeviceWireless(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDeviceWireless {
	mock := &MockDeviceWireless{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDeviceWireless is an autogenerated mock type for the DeviceWireless type
type MockDeviceWireless struct {
	mock.Mock
}

type MockDeviceWireless_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDeviceWireless) EXPECT() *MockDeviceWireless_Expecter {
	return &MockDeviceWireless_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockDeviceWireless
func (_mock *MockDeviceWireless) Delete() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDeviceWireless_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockDeviceWireless_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
func (_e *MockDeviceWireless_Expecter) Delete() *MockDeviceWireless_Delete_Call {
	return &MockDeviceWireless_Delete_Call{Call: _e.mock.On("Delete")}
}

func (_c *MockDeviceWireless_Delete_Call) Run(run func()) *MockDeviceWireless_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDeviceWireless_Delete_Call) Return(err error) *MockDeviceWireless_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDeviceWireless_Delete_Call) RunAndReturn(run func() error) *MockDeviceWireless_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Disconnect provides a mock function for the type MockDeviceWireless
func (_mock *MockDeviceWireless) Disconnect() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Disconnect")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDeviceWireless_Disconnect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Disconnect'
type MockDeviceWireless_Disconnect_Call struct {
	*mock.Call
}

// Disconnect is a helper method to define mock.On call
func (_e *MockDeviceWireless_Expecter) Disconnect() *MockDeviceWireless_Disconnect_Call {
	return &MockDeviceWireless_Disconnect_Call{Call: _e.mock.On("Disconnect")}
}

func (_c *MockDeviceWireless_Disconnect_Call) Run(run func()) *MockDeviceWireless_Disconnect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDeviceWireless_Disconnect_Call) Return(err error) *MockDeviceWireless_Disconnect_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDeviceWireless_Disconnect_Call) RunAndReturn(run func() error) *MockDeviceWireless_Disconnect_Call {
	_c.Call.Return(run)
	return _c
}

// GetAccessPoints provides a mock function for the type MockDeviceWireless
func (_mock *MockDeviceWireless) GetAccessPoints() ([]gonetworkmanager.AccessPoint, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAccessPoints")
	}

	var r0 []gonetworkmanager.AccessPoint
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]gonetworkmanager.AccessPoint, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []gonetworkmanager.AccessPoint); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]gonetworkmanager.AccessPoint)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeviceWireless_GetAccessPoints_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccessPoints'
type MockDeviceWireless_GetAccessPoints_Call struct {
	*mock.Call
}

// GetAccessPoints is a helper method to define mock.On call
func (_e *MockDeviceWireless_Expecter) GetAccessPoints() *MockDeviceWireless_GetAccessPoints_Call {
	return &MockDeviceWireless_GetAccessPoints_Call{Call: _e.mock.On("GetAccessPoints")}
}

func (_c *MockDeviceWireless_GetAccessPoints_Call) Run(run func()) *MockDeviceWireless_GetAccessPoints_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDeviceWireless_GetAccessPoints_Call) Return(accessPoints []gonetworkmanager.AccessPoint, err error) *MockDeviceWireless_GetAccessPoints_Call {
	_c.Call.Return(accessPoints, err)
	return _c
}

func (_c *MockDeviceWireless_GetAccessPoints_Call) RunAndReturn(run func() ([]gonetworkmanager.AccessPoint, error)) *MockDeviceWireless_GetAccessPoints_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllAccessPoints provides a mock function for the type MockDeviceWireless
func (_mock *MockDeviceWireless) GetAllAccessPoints() ([]gonetworkmanager.AccessPoint, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllAccessPoints")
	}

	var r0 []gonetworkmanager.AccessPoint
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]gonetworkmanager.AccessPoint, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []gonetworkmanager.AccessPoint); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]gonetworkmanager.AccessPoint)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeviceWireless_GetAllAccessPoints_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllAccessPoints'
type MockDeviceWireless_GetAllAccessPoints_Call struct {
	*mock.Call
}

// GetAllAccessPoints is a helper method to define mock.On call
func (_e *MockDeviceWireless_Expecter) GetAllAccessPoints() *MockDeviceWireless_GetAllAccessPoints_Call {
	return &MockDeviceWireless_GetAllAccessPoints_Call{Call: _e.mock.On("GetAllAccessPoints")}
}

func (_c *MockDeviceWireless_GetAllAccessPoints_Call) Run(run func()) *MockDeviceWireless_GetAllAccessPoints_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDeviceWireless_GetAllAccessPoints_Call) Return(accessPoints []gonetworkmanager.AccessPoint, err error) *MockDeviceWireless_GetAllAccessPoints_Call {
	_c.Call.Return(accessPoints, err)
	return _c
}

func (_c *MockDeviceWireless_GetAllAccessPoints_Call) RunAndReturn(run func() ([]gonetworkmanager.AccessPoint, error)) *MockDeviceWireless_GetAllAccessPoints_Call {
	_c.Call.Return(run)
	return _c
}

// GetPath provides a mock function for the type MockDeviceWireless
func (_mock *MockDeviceWireless) GetPath() dbus.ObjectPath {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPath")
	}

	var r0 dbus.ObjectPath
	if returnFunc, ok := ret.Get(0).(func() dbus.ObjectPath); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(dbus.ObjectPath)
	}
	return r0
}

// MockDeviceWireless_GetPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPath'
type MockDeviceWireless_GetPath_Call struct {
	*mock.Call
}

// GetPath is a helper method to define mock.On call
func (_e *MockDeviceWireless_Expecter) GetPath() *MockDeviceWireless_GetPath_Call {
	return &MockDeviceWireless_GetPath_Call{Call: _e.mock.On("GetPath")}
}

func (_c *MockDeviceWireless_GetPath_Call) Run(run func()) *MockDeviceWireless_GetPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDeviceWireless_GetPath_Call) Return(objectPath dbus.ObjectPath) *MockDeviceWireless_GetPath_Call {
	_c.Call.Return(objectPath)
	return _c
}

func (_c *MockDeviceWireless_GetPath_Call) RunAndReturn(run func() dbus.ObjectPath) *MockDeviceWireless_GetPath_Call {
	_c.Call.Return(run)
	return _c
}

// GetPropertyAccessPoints provides a mock function for the type MockDeviceWireless
func (_mock *MockDeviceWireless) GetPropertyAccessPoints() ([]gonetworkmanager.AccessPoint, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPropertyAccessPoints")
	}

	var r0 []gonetworkmanager.AccessPoint
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]gonetworkmanager.AccessPoint, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []gonetworkmanager.AccessPoint); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]gonetworkmanager.AccessPoint)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeviceWireless_GetPropertyAccessPoints_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPropertyAccessPoints'
type MockDeviceWireless_GetPropertyAccessPoints_Call struct {
	*mock.Call
}

// GetPropertyAccessPoints is a helper method to define mock.On call
func (_e *MockDeviceWireless_Expecter) GetPropertyAccessPoints() *MockDeviceWireless_GetPropertyAccessPoints_Call {
	return &MockDeviceWireless_GetPropertyAccessPoints_Call{Call: _e.mock.On("GetPropertyAccessPoints")}
}

func (_c *MockDeviceWireless_GetPropertyAccessPoints_Call) Run(run func()) *MockDeviceWireless_GetPropertyAccessPoints_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDeviceWireless_GetPropertyAccessPoints_Call) Return(accessPoints []gonetworkmanager.AccessPoint, err error) *MockDeviceWireless_GetPropertyAccessPoints_Call {
	_c.Call.Return(accessPoints, err)
	return _c
}

func (_c *MockDeviceWireless_GetPropertyAccessPoints_Call) RunAndReturn(run func() ([]gonetworkmanager.AccessPoint, error)) *MockDeviceWireless_GetPropertyAccessPoints_Call {
	_c.Call.Return(run)
	return _c
}

// GetPropertyActiveAccessPoint provides a mock function for the type MockDeviceWireless
func (_mock *MockDeviceWireless) GetPropertyActiveAccessPoint() (gonetworkmanager.AccessPoint, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPropertyActiveAccessPoint")
	}

	var r0 gonetworkmanager.AccessPoint
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (gonetworkmanager.AccessPoint, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() gonetworkmanager.AccessPoint); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gonetworkmanager.AccessPoint)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeviceWireless_GetPropertyActiveAccessPoint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPropertyActiveAccessPoint'
type MockDeviceWireless_GetPropertyActiveAccessPoint_Call struct {
	*mock.Call
}

// GetPropertyActiveAccessPoint is a helper method to define mock.On call
func (_e *MockDeviceWireless_Expecter) GetPropertyActiveAccessPoint() *MockDeviceWireless_GetPropertyActiveAccessPoint_Call {
	return &MockDeviceWireless_GetPropertyActiveAccessPoint_Call{Call: _e.mock.On("GetPropertyActiveAccessPoint")}
}

func (_c *MockDeviceWireless_GetPropertyActiveAccessPoint_Call) Run(run func()) *MockDeviceWireless_GetPropertyActiveAccessPoint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDeviceWireless_GetPropertyActiveAccessPoint_Call) Return(accessPoint gonetworkmanager.AccessPoint, err error) *MockDeviceWireless_GetPropertyActiveAccessPoint_Call {
	_c.Call.Return(accessPoint, err)
	return _c
}

func (_c *MockDeviceWireless_GetPropertyActiveAccessPoint_Call) RunAndReturn(run func() (gonetworkmanager.AccessPoint, error)) *MockDeviceWireless_GetPropertyActiveAccessPoint_Call {
	_c.Call.Return(run)
	return _c
}

// GetPropertyActiveConnection provides a mock function for the type MockDeviceWireless
func (_mock *MockDeviceWireless) GetPropertyActiveConnection() (gonetworkmanager.ActiveConnection, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPropertyActiveConnection")
	}

	var r0 gonetworkmanager.ActiveConnection
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (gonetworkmanager.ActiveConnection, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() gonetworkmanager.ActiveConnection); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gonetworkmanager.ActiveConnection)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeviceWireless_GetPropertyActiveConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPropertyActiveConnection'
type MockDeviceWireless_GetPropertyActiveConnection_Call struct {
	*mock.Call
}

// GetPropertyActiveConnection is a helper method to define mock.On call
func (_e *MockDeviceWireless_Expecter) GetPropertyActiveConnection() *MockDeviceWireless_GetPropertyActiveConnection_Call {
	return &MockDeviceWireless_GetPropertyActiveConnection_Call{Call: _e.mock.On("GetPropertyActiveConnection")}
}

func (_c *MockDeviceWireless_GetPropertyActiveConnection_Call) Run(run func()) *MockDeviceWireless_GetPropertyActiveConnection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDeviceWireless_GetPropertyActiveConnection_Call) Return(activeConnection gonetworkmanager.ActiveConnection, err error) *MockDeviceWireless_GetPropertyActiveConnection_Call {
	_c.Call.Return(activeConnection, err)
	return _c
}

func (_c *MockDeviceWireless_GetPropertyActiveConnection_Call) RunAndReturn(run func() (gonetworkmanager.ActiveConnection, error)) *MockDeviceWireless_GetPropertyActiveConnection_Call {
	_c.Call.Return(run)
	return _c
}

// GetPropertyAutoConnect provides a mock function for the type MockDeviceWireless
func (_mock *MockDeviceWireless) GetPropertyAutoConnect() (bool, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPropertyAutoConnect")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (bool, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeviceWireless_GetPropertyAutoConnect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPropertyAutoConnect'
type MockDeviceWireless_GetPropertyAutoConnect_Call struct {
	*mock.Call
}

// GetPropertyAutoConnect is a helper method to define mock.On call
func (_e *MockDeviceWireless_Expecter) GetPropertyAutoConnect() *MockDeviceWireless_GetPropertyAutoConnect_Call {
	return &MockDeviceWireless_GetPropertyAutoConnect_Call{Call: _e.mock.On("GetPropertyAutoConnect")}
}

func (_c *MockDeviceWireless_GetPropertyAutoConnect_Call) Run(run func()) *MockDeviceWireless_GetPropertyAutoConnect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDeviceWireless_GetPropertyAutoConnect_Call) Return(b bool, err error) *MockDeviceWireless_GetPropertyAutoConnect_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockDeviceWireless_GetPropertyAutoConnect_Call) RunAndReturn(run func() (bool, error)) *MockDeviceWireless_GetPropertyAutoConnect_Call {
	_c.Call.Return(run)
	return _c
}

// GetPropertyAvailableConnections provides a mock function for the type MockDeviceWireless
func (_mock *MockDeviceWireless) GetPropertyAvailableConnections() ([]gonetworkmanager.Connection, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPropertyAvailableConnections")
	}

	var r0 []gonetworkmanager.Connection
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]gonetworkmanager.Connection, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []gonetworkmanager.Connection); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]gonetworkmanager.Connection)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeviceWireless_GetPropertyAvailableConnections_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPropertyAvailableConnections'
type MockDeviceWireless_GetPropertyAvailableConnections_Call struct {
	*mock.Call
}

// GetPropertyAvailableConnections is a helper method to define mock.On call
func (_e *MockDeviceWireless_Expecter) GetPropertyAvailableConnections() *MockDeviceWireless_GetPropertyAvailableConnections_Call {
	return &MockDeviceWireless_GetPropertyAvailableConnections_Call{Call: _e.mock.On("GetPropertyAvailableConnections")}
}

func (_c *MockDeviceWireless_GetPropertyAvailableConnections_Call) Run(run func()) *MockDeviceWireless_GetPropertyAvailableConnections_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDeviceWireless_GetPropertyAvailableConnections_Call) Return(connections []gonetworkmanager.Connection, err error) *MockDeviceWireless_GetPropertyAvailableConnections_Call {
	_c.Call.Return(connections, err)
	return _c
}

func (_c *MockDeviceWireless_GetPropertyAvailableConnections_Call) RunAndReturn(run func() ([]gonetworkmanager.Connection, error)) *MockDeviceWireless_GetPropertyAvailableConnections_Call {
	_c.Call.Return(run)
	return _c
}

// GetPropertyBitrate provides a mock function for the type MockDeviceWireless
func (_mock *MockDeviceWireless) GetPropertyBitrate() (uint32, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPropertyBitrate")
	}

	var r0 uint32
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (uint32, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() uint32); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(uint32)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeviceWireless_GetPropertyBitrate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPropertyBitrate'
type MockDeviceWireless_GetPropertyBitrate_Call struct {
	*mock.Call
}

// GetPropertyBitrate is a helper method to define mock.On call
func (_e *MockDeviceWireless_Expecter) GetPropertyBitrate() *MockDeviceWireless_GetPropertyBitrate_Call {
	return &MockDeviceWireless_GetPropertyBitrate_Call{Call: _e.mock.On("GetPropertyBitrate")}
}

func (_c *MockDeviceWireless_GetPropertyBitrate_Call) Run(run func()) *MockDeviceWireless_GetPropertyBitrate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDeviceWireless_GetPropertyBitrate_Call) Return(v uint32, err error) *MockDeviceWireless_GetPropertyBitrate_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockDeviceWireless_GetPropertyBitrate_Call) RunAndReturn(run func() (uint32, error)) *MockDeviceWireless_GetPropertyBitrate_Call {
	_c.Call.Return(run)
	return _c
}

// GetPropertyDHCP4Config provides a mock function for the type MockDeviceWireless
func (_mock *MockDeviceWireless) GetPropertyDHCP4Config() (gonetworkmanager.DHCP4Config, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPropertyDHCP4Config")
	}

	var r0 gonetworkmanager.DHCP4Config
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (gonetworkmanager.DHCP4Config, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() gonetworkmanager.DHCP4Config); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gonetworkmanager.DHCP4Config)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeviceWireless_GetPropertyDHCP4Config_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPropertyDHCP4Config'
type MockDeviceWireless_GetPropertyDHCP4Config_Call struct {
	*mock.Call
}

// GetPropertyDHCP4Config is a helper method to define mock.On call
func (_e *MockDeviceWireless_Expecter) GetPropertyDHCP4Config() *MockDeviceWireless_GetPropertyDHCP4Config_Call {
	return &MockDeviceWireless_GetPropertyDHCP4Config_Call{Call: _e.mock.On("GetPropertyDHCP4Config")}
}

func (_c *MockDeviceWireless_GetPropertyDHCP4Config_Call) Run(run func()) *MockDeviceWireless_GetPropertyDHCP4Config_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDeviceWireless_GetPropertyDHCP4Config_Call) Return(dHCP4Config gonetworkmanager.DHCP4Config, err error) *MockDeviceWireless_GetPropertyDHCP4Config_Call {
	_c.Call.Return(dHCP4Config, err)
	return _c
}

func (_c *MockDeviceWireless_GetPropertyDHCP4Config_Call) RunAndReturn(run func() (gonetworkmanager.DHCP4Config, error)) *MockDeviceWireless_GetPropertyDHCP4Config_Call {
	_c.Call.Return(run)
	return _c
}

// GetPropertyDHCP6Config provides a mock function for the type MockDeviceWireless
func (_mock *MockDeviceWireless) GetPropertyDHCP6Config() (gonetworkmanager.DHCP6Config, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPropertyDHCP6Config")
	}

	var r0 gonetworkmanager.DHCP6Config
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (gonetworkmanager.DHCP6Config, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() gonetworkmanager.DHCP6Config); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gonetworkmanager.DHCP6Config)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeviceWireless_GetPropertyDHCP6Config_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPropertyDHCP6Config'
type MockDeviceWireless_GetPropertyDHCP6Config_Call struct {
	*mock.Call
}

// GetPropertyDHCP6Config is a helper method to define mock.On call
func (_e *MockDeviceWireless_Expecter) GetPropertyDHCP6Config() *MockDeviceWireless_GetPropertyDHCP6Config_Call {
	return &MockDeviceWireless_GetPropertyDHCP6Config_Call{Call: _e.mock.On("GetPropertyDHCP6Config")}
}

func (_c *MockDeviceWireless_GetPropertyDHCP6Config_Call) Run(run func()) *MockDeviceWireless_GetPropertyDHCP6Config_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDeviceWireless_GetPropertyDHCP6Config_Call) Return(dHCP6Config gonetworkmanager.DHCP6Config, err error) *MockDeviceWireless_GetPropertyDHCP6Config_Call {
	_c.Call.Return(dHCP6Config, err)
	return _c
}

func (_c *MockDeviceWireless_GetPropertyDHCP6Config_Call) RunAndReturn(run func() (gonetworkmanager.DHCP6Config, error)) *MockDeviceWireless_GetPropertyDHCP6Config_Call {
	_c.Call.Return(run)
	return _c
}

// GetPropertyDeviceType provides a mock function for the type MockDeviceWireless
func (_mock *MockDeviceWireless) GetPropertyDeviceType() (gonetworkmanager.NmDeviceType, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPropertyDeviceType")
	}

	var r0 gonetworkmanager.NmDeviceType
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (gonetworkmanager.NmDeviceType, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() gonetworkmanager.NmDeviceType); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(gonetworkmanager.NmDeviceType)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeviceWireless_GetPropertyDeviceType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPropertyDeviceType'
type MockDeviceWireless_GetPropertyDeviceType_Call struct {
	*mock.Call
}

// GetPropertyDeviceType is a helper method to define mock.On call
func (_e *MockDeviceWireless_Expecter) GetPropertyDeviceType() *MockDeviceWireless_GetPropertyDeviceType_Call {
	return &MockDeviceWireless_GetPropertyDeviceType_Call{Call: _e.mock.On("GetPropertyDeviceType")}
}

func (_c *MockDeviceWireless_GetPropertyDeviceType_Call) Run(run func()) *MockDeviceWireless_GetPropertyDeviceType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDeviceWireless_GetPropertyDeviceType_Call) Return(nmDeviceType gonetworkmanager.NmDeviceType, err error) *MockDeviceWireless_GetPropertyDeviceType_Call {
	_c.Call.Return(nmDeviceType, err)
	return _c
}

func (_c *MockDeviceWireless_GetPropertyDeviceType_Call) RunAndReturn(run func() (gonetworkmanager.NmDeviceType, error)) *MockDeviceWireless_GetPropertyDeviceType_Call {
	_c.Call.Return(run)
	return _c
}

// GetPropertyDriver provides a mock function for the type MockDeviceWireless
func (_mock *MockDeviceWireless) GetPropertyDriver() (string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPropertyDriver")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeviceWireless_GetPropertyDriver_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPropertyDriver'
type MockDeviceWireless_GetPropertyDriver_Call struct {
	*mock.Call
}

// GetPropertyDriver is a helper method to define mock.On call
func (_e *MockDeviceWireless_Expecter) GetPropertyDriver() *MockDeviceWireless_GetPropertyDriver_Call {
	return &MockDeviceWireless_GetPropertyDriver_Call{Call: _e.mock.On("GetPropertyDriver")}
}

func (_c *MockDeviceWireless_GetPropertyDriver_Call) Run(run func()) *MockDeviceWireless_GetPropertyDriver_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDeviceWireless_GetPropertyDriver_Call) Return(s string, err error) *MockDeviceWireless_GetPropertyDriver_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockDeviceWireless_GetPropertyDriver_Call) RunAndReturn(run func() (string, error)) *MockDeviceWireless_GetPropertyDriver_Call {
	_c.Call.Return(run)
	return _c
}

// GetPropertyDriverVersion provides a mock function for the type MockDeviceWireless
func (_mock *MockDeviceWireless) GetPropertyDriverVersion() (string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPropertyDriverVersion")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeviceWireless_GetPropertyDriverVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPropertyDriverVersion'
type MockDeviceWireless_GetPropertyDriverVersion_Call struct {
	*mock.Call
}

// GetPropertyDriverVersion is a helper method to define mock.On call
func (_e *MockDeviceWireless_Expecter) GetPropertyDriverVersion() *MockDeviceWireless_GetPropertyDriverVersion_Call {
	return &MockDeviceWireless_GetPropertyDriverVersion_Call{Call: _e.mock.On("GetPropertyDriverVersion")}
}

func (_c *MockDeviceWireless_GetPropertyDriverVersion_Call) Run(run func()) *MockDeviceWireless_GetPropertyDriverVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDeviceWireless_GetPropertyDriverVersion_Call) Return(s string, err error) *MockDeviceWireless_GetPropertyDriverVersion_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockDeviceWireless_GetPropertyDriverVersion_Call) RunAndReturn(run func() (string, error)) *MockDeviceWireless_GetPropertyDriverVersion_Call {
	_c.Call.Return(run)
	return _c
}

// GetPropertyFirmwareMissing provides a mock function for the type MockDeviceWireless
func (_mock *MockDeviceWireless) GetPropertyFirmwareMissing() (bool, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPropertyFirmwareMissing")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (bool, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeviceWireless_GetPropertyFirmwareMissing_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPropertyFirmwareMissing'
type MockDeviceWireless_GetPropertyFirmwareMissing_Call struct {
	*mock.Call
}

// GetPropertyFirmwareMissing is a helper method to define mock.On call
func (_e *MockDeviceWireless_Expecter) GetPropertyFirmwareMissing() *MockDeviceWireless_GetPropertyFirmwareMissing_Call {
	return &MockDeviceWireless_GetPropertyFirmwareMissing_Call{Call: _e.mock.On("GetPropertyFirmwareMissing")}
}

func (_c *MockDeviceWireless_GetPropertyFirmwareMissing_Call) Run(run func()) *MockDeviceWireless_GetPropertyFirmwareMissing_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDeviceWireless_GetPropertyFirmwareMissing_Call) Return(b bool, err error) *MockDeviceWireless_GetPropertyFirmwareMissing_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockDeviceWireless_GetPropertyFirmwareMissing_Call) RunAndReturn(run func() (bool, error)) *MockDeviceWireless_GetPropertyFirmwareMissing_Call {
	_c.Call.Return(run)
	return _c
}

// GetPropertyFirmwareVersion provides a mock function for the type MockDeviceWireless
func (_mock *MockDeviceWireless) GetPropertyFirmwareVersion() (string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPropertyFirmwareVersion")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeviceWireless_GetPropertyFirmwareVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPropertyFirmwareVersion'
type MockDeviceWireless_GetPropertyFirmwareVersion_Call struct {
	*mock.Call
}

// GetPropertyFirmwareVersion is a helper method to define mock.On call
func (_e *MockDeviceWireless_Expecter) GetPropertyFirmwareVersion() *MockDeviceWireless_GetPropertyFirmwareVersion_Call {
	return &MockDeviceWireless_GetPropertyFirmwareVersion_Call{Call: _e.mock.On("GetPropertyFirmwareVersion")}
}

func (_c *MockDeviceWireless_GetPropertyFirmwareVersion_Call) Run(run func()) *MockDeviceWireless_GetPropertyFirmwareVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDeviceWireless_GetPropertyFirmwareVersion_Call) Return(s string, err error) *MockDeviceWireless_GetPropertyFirmwareVersion_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockDeviceWireless_GetPropertyFirmwareVersion_Call) RunAndReturn(run func() (string, error)) *MockDeviceWireless_GetPropertyFirmwareVersion_Call {
	_c.Call.Return(run)
	return _c
}

// GetPropertyHwAddress provides a mock function for the type MockDeviceWireless
func (_mock *MockDeviceWireless) GetPropertyHwAddress() (string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPropertyHwAddress")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeviceWireless_GetPropertyHwAddress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPropertyHwAddress'
type MockDeviceWireless_GetPropertyHwAddress_Call struct {
	*mock.Call
}

// GetPropertyHwAddress is a helper method to define mock.On call
func (_e *MockDeviceWireless_Expecter) GetPropertyHwAddress() *MockDeviceWireless_GetPropertyHwAddress_Call {
	return &MockDeviceWireless_GetPropertyHwAddress_Call{Call: _e.mock.On("GetPropertyHwAddress")}
}

func (_c *MockDeviceWireless_GetPropertyHwAddress_Call) Run(run func()) *MockDeviceWireless_GetPropertyHwAddress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDeviceWireless_GetPropertyHwAddress_Call) Return(s string, err error) *MockDeviceWireless_GetPropertyHwAddress_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockDeviceWireless_GetPropertyHwAddress_Call) RunAndReturn(run func() (string, error)) *MockDeviceWireless_GetPropertyHwAddress_Call {
	_c.Call.Return(run)
	return _c
}

// GetPropertyIP4Config provides a mock function for the type MockDeviceWireless
func (_mock *MockDeviceWireless) GetPropertyIP4Config() (gonetworkmanager.IP4Config, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPropertyIP4Config")
	}

	var r0 gonetworkmanager.IP4Config
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (gonetworkmanager.IP4Config, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() gonetworkmanager.IP4Config); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gonetworkmanager.IP4Config)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeviceWireless_GetPropertyIP4Config_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPropertyIP4Config'
type MockDeviceWireless_GetPropertyIP4Config_Call struct {
	*mock.Call
}

// GetPropertyIP4Config is a helper method to define mock.On call
func (_e *MockDeviceWireless_Expecter) GetPropertyIP4Config() *MockDeviceWireless_GetPropertyIP4Config_Call {
	return &MockDeviceWireless_GetPropertyIP4Config_Call{Call: _e.mock.On("GetPropertyIP4Config")}
}

func (_c *MockDeviceWireless_GetPropertyIP4Config_Call) Run(run func()) *MockDeviceWireless_GetPropertyIP4Config_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDeviceWireless_GetPropertyIP4Config_Call) Return(iP4Config gonetworkmanager.IP4Config, err error) *MockDeviceWireless_GetPropertyIP4Config_Call {
	_c.Call.Return(iP4Config, err)
	return _c
}

func (_c *MockDeviceWireless_GetPropertyIP4Config_Call) RunAndReturn(run func() (gonetworkmanager.IP4Config, error)) *MockDeviceWireless_GetPropertyIP4Config_Call {
	_c.Call.Return(run)
	return _c
}

// GetPropertyIP6Config provides a mock function for the type MockDeviceWireless
func (_mock *MockDeviceWireless) GetPropertyIP6Config() (gonetworkmanager.IP6Config, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPropertyIP6Config")
	}

	var r0 gonetworkmanager.IP6Config
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (gonetworkmanager.IP6Config, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() gonetworkmanager.IP6Config); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gonetworkmanager.IP6Config)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeviceWireless_GetPropertyIP6Config_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPropertyIP6Config'
type MockDeviceWireless_GetPropertyIP6Config_Call struct {
	*mock.Call
}

// GetPropertyIP6Config is a helper method to define mock.On call
func (_e *MockDeviceWireless_Expecter) GetPropertyIP6Config() *MockDeviceWireless_GetPropertyIP6Config_Call {
	return &MockDeviceWireless_GetPropertyIP6Config_Call{Call: _e.mock.On("GetPropertyIP6Config")}
}

func (_c *MockDeviceWireless_GetPropertyIP6Config_Call) Run(run func()) *MockDeviceWireless_GetPropertyIP6Config_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDeviceWireless_GetPropertyIP6Config_Call) Return(iP6Config gonetworkmanager.IP6Config, err error) *MockDeviceWireless_GetPropertyIP6Config_Call {
	_c.Call.Return(iP6Config, err)
	return _c
}

func (_c *MockDeviceWireless_GetPropertyIP6Config_Call) RunAndReturn(run func() (gonetworkmanager.IP6Config, error)) *MockDeviceWireless_GetPropertyIP6Config_Call {
	_c.Call.Return(run)
	return _c
}

// GetPropertyInterface provides a mock function for the type MockDeviceWireless
func (_mock *MockDeviceWireless) GetPropertyInterface() (string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPropertyInterface")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeviceWireless_GetPropertyInterface_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPropertyInterface'
type MockDeviceWireless_GetPropertyInterface_Call struct {
	*mock.Call
}

// GetPropertyInterface is a helper method to define mock.On call
func (_e *MockDeviceWireless_Expecter) GetPropertyInterface() *MockDeviceWireless_GetPropertyInterface_Call {
	return &MockDeviceWireless_GetPropertyInterface_Call{Call: _e.mock.On("GetPropertyInterface")}
}

func (_c *MockDeviceWireless_GetPropertyInterface_Call) Run(run func()) *MockDeviceWireless_GetPropertyInterface_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDeviceWireless_GetPropertyInterface_Call) Return(s string, err error) *MockDeviceWireless_GetPropertyInterface_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockDeviceWireless_GetPropertyInterface_Call) RunAndReturn(run func() (string, error)) *MockDeviceWireless_GetPropertyInterface_Call {
	_c.Call.Return(run)
	return _c
}

// GetPropertyIp4Connectivity provides a mock function for the type MockDeviceWireless
func (_mock *MockDeviceWireless) GetPropertyIp4Connectivity() (gonetworkmanager.NmConnectivity, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPropertyIp4Connectivity")
	}

	var r0 gonetworkmanager.NmConnectivity
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (gonetworkmanager.NmConnectivity, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() gonetworkmanager.NmConnectivity); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(gonetworkmanager.NmConnectivity)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeviceWireless_GetPropertyIp4Connectivity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPropertyIp4Connectivity'
type MockDeviceWireless_GetPropertyIp4Connectivity_Call struct {
	*mock.Call
}

// GetPropertyIp4Connectivity is a helper method to define mock.On call
func (_e *MockDeviceWireless_Expecter) GetPropertyIp4Connectivity() *MockDeviceWireless_GetPropertyIp4Connectivity_Call {
	return &MockDeviceWireless_GetPropertyIp4Connectivity_Call{Call: _e.mock.On("GetPropertyIp4Connectivity")}
}

func (_c *MockDeviceWireless_GetPropertyIp4Connectivity_Call) Run(run func()) *MockDeviceWireless_GetPropertyIp4Connectivity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDeviceWireless_GetPropertyIp4Connectivity_Call) Return(nmConnectivity gonetworkmanager.NmConnectivity, err error) *MockDeviceWireless_GetPropertyIp4Connectivity_Call {
	_c.Call.Return(nmConnectivity, err)
	return _c
}

func (_c *MockDeviceWireless_GetPropertyIp4Connectivity_Call) RunAndReturn(run func() (gonetworkmanager.NmConnectivity, error)) *MockDeviceWireless_GetPropertyIp4Connectivity_Call {
	_c.Call.Return(run)
	return _c
}

// GetPropertyIpInterface provides a mock function for the type MockDeviceWireless
func (_mock *MockDeviceWireless) GetPropertyIpInterface() (string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPropertyIpInterface")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeviceWireless_GetPropertyIpInterface_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPropertyIpInterface'
type MockDeviceWireless_GetPropertyIpInterface_Call struct {
	*mock.Call
}

// GetPropertyIpInterface is a helper method to define mock.On call
func (_e *MockDeviceWireless_Expecter) GetPropertyIpInterface() *MockDeviceWireless_GetPropertyIpInterface_Call {
	return &MockDeviceWireless_GetPropertyIpInterface_Call{Call: _e.mock.On("GetPropertyIpInterface")}
}

func (_c *MockDeviceWireless_GetPropertyIpInterface_Call) Run(run func()) *MockDeviceWireless_GetPropertyIpInterface_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDeviceWireless_GetPropertyIpInterface_Call) Return(s string, err error) *MockDeviceWireless_GetPropertyIpInterface_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockDeviceWireless_GetPropertyIpInterface_Call) RunAndReturn(run func() (string, error)) *MockDeviceWireless_GetPropertyIpInterface_Call {
	_c.Call.Return(run)
	return _c
}

// GetPropertyLastScan provides a mock function for the type MockDeviceWireless
func (_mock *MockDeviceWireless) GetPropertyLastScan() (int64, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPropertyLastScan")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (int64, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() int64); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeviceWireless_GetPropertyLastScan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPropertyLastScan'
type MockDeviceWireless_GetPropertyLastScan_Call struct {
	*mock.Call
}

// GetPropertyLastScan is a helper method to define mock.On call
func (_e *MockDeviceWireless_Expecter) GetPropertyLastScan() *MockDeviceWireless_GetPropertyLastScan_Call {
	return &MockDeviceWireless_GetPropertyLastScan_Call{Call: _e.mock.On("GetPropertyLastScan")}
}

func (_c *MockDeviceWireless_GetPropertyLastScan_Call) Run(run func()) *MockDeviceWireless_GetPropertyLastScan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDeviceWireless_GetPropertyLastScan_Call) Return(n int64, err error) *MockDeviceWireless_GetPropertyLastScan_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockDeviceWireless_GetPropertyLastScan_Call) RunAndReturn(run func() (int64, error)) *MockDeviceWireless_GetPropertyLastScan_Call {
	_c.Call.Return(run)
	return _c
}

// GetPropertyManaged provides a mock function for the type MockDeviceWireless
func (_mock *MockDeviceWireless) GetPropertyManaged() (bool, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPropertyManaged")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (bool, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeviceWireless_GetPropertyManaged_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPropertyManaged'
type MockDeviceWireless_GetPropertyManaged_Call struct {
	*mock.Call
}

// GetPropertyManaged is a helper method to define mock.On call
func (_e *MockDeviceWireless_Expecter) GetPropertyManaged() *MockDeviceWireless_GetPropertyManaged_Call {
	return &MockDeviceWireless_GetPropertyManaged_Call{Call: _e.mock.On("GetPropertyManaged")}
}

func (_c *MockDeviceWireless_GetPropertyManaged_Call) Run(run func()) *MockDeviceWireless_GetPropertyManaged_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDeviceWireless_GetPropertyManaged_Call) Return(b bool, err error) *MockDeviceWireless_GetPropertyManaged_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockDeviceWireless_GetPropertyManaged_Call) RunAndReturn(run func() (bool, error)) *MockDeviceWireless_GetPropertyManaged_Call {
	_c.Call.Return(run)
	return _c
}

// GetPropertyMode provides a mock function for the type MockDeviceWireless
func (_mock *MockDeviceWireless) GetPropertyMode() (gonetworkmanager.Nm80211Mode, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPropertyMode")
	}

	var r0 gonetworkmanager.Nm80211Mode
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (gonetworkmanager.Nm80211Mode, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() gonetworkmanager.Nm80211Mode); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(gonetworkmanager.Nm80211Mode)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeviceWireless_GetPropertyMode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPropertyMode'
type MockDeviceWireless_GetPropertyMode_Call struct {
	*mock.Call
}

// GetPropertyMode is a helper method to define mock.On call
func (_e *MockDeviceWireless_Expecter) GetPropertyMode() *MockDeviceWireless_GetPropertyMode_Call {
	return &MockDeviceWireless_GetPropertyMode_Call{Call: _e.mock.On("GetPropertyMode")}
}

func (_c *MockDeviceWireless_GetPropertyMode_Call) Run(run func()) *MockDeviceWireless_GetPropertyMode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDeviceWireless_GetPropertyMode_Call) Return(nm80211Mode gonetworkmanager.Nm80211Mode, err error) *MockDeviceWireless_GetPropertyMode_Call {
	_c.Call.Return(nm80211Mode, err)
	return _c
}

func (_c *MockDeviceWireless_GetPropertyMode_Call) RunAndReturn(run func() (gonetworkmanager.Nm80211Mode, error)) *MockDeviceWireless_GetPropertyMode_Call {
	_c.Call.Return(run)
	return _c
}

// GetPropertyMtu provides a mock function for the type MockDeviceWireless
func (_mock *MockDeviceWireless) GetPropertyMtu() (uint32, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPropertyMtu")
	}

	var r0 uint32
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (uint32, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() uint32); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(uint32)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeviceWireless_GetPropertyMtu_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPropertyMtu'
type MockDeviceWireless_GetPropertyMtu_Call struct {
	*mock.Call
}

// GetPropertyMtu is a helper method to define mock.On call
func (_e *MockDeviceWireless_Expecter) GetPropertyMtu() *MockDeviceWireless_GetPropertyMtu_Call {
	return &MockDeviceWireless_GetPropertyMtu_Call{Call: _e.mock.On("GetPropertyMtu")}
}

func (_c *MockDeviceWireless_GetPropertyMtu_Call) Run(run func()) *MockDeviceWireless_GetPropertyMtu_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDeviceWireless_GetPropertyMtu_Call) Return(v uint32, err error) *MockDeviceWireless_GetPropertyMtu_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockDeviceWireless_GetPropertyMtu_Call) RunAndReturn(run func() (uint32, error)) *MockDeviceWireless_GetPropertyMtu_Call {
	_c.Call.Return(run)
	return _c
}

// GetPropertyNmPluginMissing provides a mock function for the type MockDeviceWireless
func (_mock *MockDeviceWireless) GetPropertyNmPluginMissing() (bool, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPropertyNmPluginMissing")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (bool, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeviceWireless_GetPropertyNmPluginMissing_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPropertyNmPluginMissing'
type MockDeviceWireless_GetPropertyNmPluginMissing_Call struct {
	*mock.Call
}

// GetPropertyNmPluginMissing is a helper method to define mock.On call
func (_e *MockDeviceWireless_Expecter) GetPropertyNmPluginMissing() *MockDeviceWireless_GetPropertyNmPluginMissing_Call {
	return &MockDeviceWireless_GetPropertyNmPluginMissing_Call{Call: _e.mock.On("GetPropertyNmPluginMissing")}
}

func (_c *MockDeviceWireless_GetPropertyNmPluginMissing_Call) Run(run func()) *MockDeviceWireless_GetPropertyNmPluginMissing_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDeviceWireless_GetPropertyNmPluginMissing_Call) Return(b bool, err error) *MockDeviceWireless_GetPropertyNmPluginMissing_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockDeviceWireless_GetPropertyNmPluginMissing_Call) RunAndReturn(run func() (bool, error)) *MockDeviceWireless_GetPropertyNmPluginMissing_Call {
	_c.Call.Return(run)
	return _c
}

// GetPropertyPermHwAddress provides a mock function for the type MockDeviceWireless
func (_mock *MockDeviceWireless) GetPropertyPermHwAddress() (string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPropertyPermHwAddress")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeviceWireless_GetPropertyPermHwAddress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPropertyPermHwAddress'
type MockDeviceWireless_GetPropertyPermHwAddress_Call struct {
	*mock.Call
}

// GetPropertyPermHwAddress is a helper method to define mock.On call
func (_e *MockDeviceWireless_Expecter) GetPropertyPermHwAddress() *MockDeviceWireless_GetPropertyPermHwAddress_Call {
	return &MockDeviceWireless_GetPropertyPermHwAddress_Call{Call: _e.mock.On("GetPropertyPermHwAddress")}
}

func (_c *MockDeviceWireless_GetPropertyPermHwAddress_Call) Run(run func()) *MockDeviceWireless_GetPropertyPermHwAddress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDeviceWireless_GetPropertyPermHwAddress_Call) Return(s string, err error) *MockDeviceWireless_GetPropertyPermHwAddress_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockDeviceWireless_GetPropertyPermHwAddress_Call) RunAndReturn(run func() (string, error)) *MockDeviceWireless_GetPropertyPermHwAddress_Call {
	_c.Call.Return(run)
	return _c
}

// GetPropertyPhysicalPortId provides a mock function for the type MockDeviceWireless
func (_mock *MockDeviceWireless) GetPropertyPhysicalPortId() (string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPropertyPhysicalPortId")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeviceWireless_GetPropertyPhysicalPortId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPropertyPhysicalPortId'
type MockDeviceWireless_GetPropertyPhysicalPortId_Call struct {
	*mock.Call
}

// GetPropertyPhysicalPortId is a helper method to define mock.On call
func (_e *MockDeviceWireless_Expecter) GetPropertyPhysicalPortId() *MockDeviceWireless_GetPropertyPhysicalPortId_Call {
	return &MockDeviceWireless_GetPropertyPhysicalPortId_Call{Call: _e.mock.On("GetPropertyPhysicalPortId")}
}

func (_c *MockDeviceWireless_GetPropertyPhysicalPortId_Call) Run(run func()) *MockDeviceWireless_GetPropertyPhysicalPortId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDeviceWireless_GetPropertyPhysicalPortId_Call) Return(s string, err error) *MockDeviceWireless_GetPropertyPhysicalPortId_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockDeviceWireless_GetPropertyPhysicalPortId_Call) RunAndReturn(run func() (string, error)) *MockDeviceWireless_GetPropertyPhysicalPortId_Call {
	_c.Call.Return(run)
	return _c
}

// GetPropertyReal provides a mock function for the type MockDeviceWireless
func (_mock *MockDeviceWireless) GetPropertyReal() (bool, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPropertyReal")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (bool, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeviceWireless_GetPropertyReal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPropertyReal'
type MockDeviceWireless_GetPropertyReal_Call struct {
	*mock.Call
}

// GetPropertyReal is a helper method to define mock.On call
func (_e *MockDeviceWireless_Expecter) GetPropertyReal() *MockDeviceWireless_GetPropertyReal_Call {
	return &MockDeviceWireless_GetPropertyReal_Call{Call: _e.mock.On("GetPropertyReal")}
}

func (_c *MockDeviceWireless_GetPropertyReal_Call) Run(run func()) *MockDeviceWireless_GetPropertyReal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDeviceWireless_GetPropertyReal_Call) Return(b bool, err error) *MockDeviceWireless_GetPropertyReal_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockDeviceWireless_GetPropertyReal_Call) RunAndReturn(run func() (bool, error)) *MockDeviceWireless_GetPropertyReal_Call {
	_c.Call.Return(run)
	return _c
}

// GetPropertyState provides a mock function for the type MockDeviceWireless
func (_mock *MockDeviceWireless) GetPropertyState() (gonetworkmanager.NmDeviceState, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPropertyState")
	}

	var r0 gonetworkmanager.NmDeviceState
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (gonetworkmanager.NmDeviceState, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() gonetworkmanager.NmDeviceState); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(gonetworkmanager.NmDeviceState)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeviceWireless_GetPropertyState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPropertyState'
type MockDeviceWireless_GetPropertyState_Call struct {
	*mock.Call
}

// GetPropertyState is a helper method to define mock.On call
func (_e *MockDeviceWireless_Expecter) GetPropertyState() *MockDeviceWireless_GetPropertyState_Call {
	return &MockDeviceWireless_GetPropertyState_Call{Call: _e.mock.On("GetPropertyState")}
}

func (_c *MockDeviceWireless_GetPropertyState_Call) Run(run func()) *MockDeviceWireless_GetPropertyState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDeviceWireless_GetPropertyState_Call) Return(nmDeviceState gonetworkmanager.NmDeviceState, err error) *MockDeviceWireless_GetPropertyState_Call {
	_c.Call.Return(nmDeviceState, err)
	return _c
}

func (_c *MockDeviceWireless_GetPropertyState_Call) RunAndReturn(run func() (gonetworkmanager.NmDeviceState, error)) *MockDeviceWireless_GetPropertyState_Call {
	_c.Call.Return(run)
	return _c
}

// GetPropertyUdi provides a mock function for the type MockDeviceWireless
func (_mock *MockDeviceWireless) GetPropertyUdi() (string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPropertyUdi")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeviceWireless_GetPropertyUdi_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPropertyUdi'
type MockDeviceWireless_GetPropertyUdi_Call struct {
	*mock.Call
}

// GetPropertyUdi is a helper method to define mock.On call
func (_e *MockDeviceWireless_Expecter) GetPropertyUdi() *MockDeviceWireless_GetPropertyUdi_Call {
	return &MockDeviceWireless_GetPropertyUdi_Call{Call: _e.mock.On("GetPropertyUdi")}
}

func (_c *MockDeviceWireless_GetPropertyUdi_Call) Run(run func()) *MockDeviceWireless_GetPropertyUdi_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDeviceWireless_GetPropertyUdi_Call) Return(s string, err error) *MockDeviceWireless_GetPropertyUdi_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockDeviceWireless_GetPropertyUdi_Call) RunAndReturn(run func() (string, error)) *MockDeviceWireless_GetPropertyUdi_Call {
	_c.Call.Return(run)
	return _c
}

// GetPropertyWirelessCapabilities provides a mock function for the type MockDeviceWireless
func (_mock *MockDeviceWireless) GetPropertyWirelessCapabilities() (uint32, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPropertyWirelessCapabilities")
	}

	var r0 uint32
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (uint32, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() uint32); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(uint32)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeviceWireless_GetPropertyWirelessCapabilities_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPropertyWirelessCapabilities'
type MockDeviceWireless_GetPropertyWirelessCapabilities_Call struct {
	*mock.Call
}

// GetPropertyWirelessCapabilities is a helper method to define mock.On call
func (_e *MockDeviceWireless_Expecter) GetPropertyWirelessCapabilities() *MockDeviceWireless_GetPropertyWirelessCapabilities_Call {
	return &MockDeviceWireless_GetPropertyWirelessCapabilities_Call{Call: _e.mock.On("GetPropertyWirelessCapabilities")}
}

func (_c *MockDeviceWireless_GetPropertyWirelessCapabilities_Call) Run(run func()) *MockDeviceWireless_GetPropertyWirelessCapabilities_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDeviceWireless_GetPropertyWirelessCapabilities_Call) Return(v uint32, err error) *MockDeviceWireless_GetPropertyWirelessCapabilities_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockDeviceWireless_GetPropertyWirelessCapabilities_Call) RunAndReturn(run func() (uint32, error)) *MockDeviceWireless_GetPropertyWirelessCapabilities_Call {
	_c.Call.Return(run)
	return _c
}

// MarshalJSON provides a mock function for the type MockDeviceWireless
func (_mock *MockDeviceWireless) MarshalJSON() ([]byte, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for MarshalJSON")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]byte, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []byte); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeviceWireless_MarshalJSON_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarshalJSON'
type MockDeviceWireless_MarshalJSON_Call struct {
	*mock.Call
}

// MarshalJSON is a helper method to define mock.On call
func (_e *MockDeviceWireless_Expecter) MarshalJSON() *MockDeviceWireless_MarshalJSON_Call {
	return &MockDeviceWireless_MarshalJSON_Call{Call: _e.mock.On("MarshalJSON")}
}

func (_c *MockDeviceWireless_MarshalJSON_Call) Run(run func()) *MockDeviceWireless_MarshalJSON_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDeviceWireless_MarshalJSON_Call) Return(bytes []byte, err error) *MockDeviceWireless_MarshalJSON_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockDeviceWireless_MarshalJSON_Call) RunAndReturn(run func() ([]byte, error)) *MockDeviceWireless_MarshalJSON_Call {
	_c.Call.Return(run)
	return _c
}

// Reapply provides a mock function for the type MockDeviceWireless
func (_mock *MockDeviceWireless) Reapply(connection gonetworkmanager.Connection, versionId uint64, flags uint32) error {
	ret := _mock.Called(connection, versionId, flags)

	if len(ret) == 0 {
		panic("no return value specified for Reapply")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(gonetworkmanager.Connection, uint64, uint32) error); ok {
		r0 = returnFunc(connection, versionId, flags)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDeviceWireless_Reapply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reapply'
type MockDeviceWireless_Reapply_Call struct {
	*mock.Call
}

// Reapply is a helper method to define mock.On call
//   - connection gonetworkmanager.Connection
//   - versionId uint64
//   - flags uint32
func (_e *MockDeviceWireless_Expecter) Reapply(connection any, versionId any, flags any) *MockDeviceWireless_Reapply_Call {
	return &MockDeviceWireless_Reapply_Call{Call: _e.mock.On("Reapply", connection, versionId, flags)}
}

func (_c *MockDeviceWireless_Reapply_Call) Run(run func(connection gonetworkmanager.Connection, versionId uint64, flags uint32)) *MockDeviceWireless_Reapply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 gonetworkmanager.Connection
		if args[0] != nil {
			arg0 = args[0].(gonetworkmanager.Connection)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 uint32
		if args[2] != nil {
			arg2 = args[2].(uint32)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDeviceWireless_Reapply_Call) Return(err error) *MockDeviceWireless_Reapply_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDeviceWireless_Reapply_Call) RunAndReturn(run func(connection gonetworkmanager.Connection, versionId uint64, flags uint32) error) *MockDeviceWireless_Reapply_Call {
	_c.Call.Return(run)
	return _c
}

// RequestScan provides a mock function for the type MockDeviceWireless
func (_mock *MockDeviceWireless) RequestScan() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for RequestScan")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDeviceWireless_RequestScan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequestScan'
type MockDeviceWireless_RequestScan_Call struct {
	*mock.Call
}

// RequestScan is a helper method to define mock.On call
func (_e *MockDeviceWireless_Expecter) RequestScan() *MockDeviceWireless_RequestScan_Call {
	return &MockDeviceWireless_RequestScan_Call{Call: _e.mock.On("RequestScan")}
}

func (_c *MockDeviceWireless_RequestScan_Call) Run(run func()) *MockDeviceWireless_RequestScan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDeviceWireless_RequestScan_Call) Return(err error) *MockDeviceWireless_RequestScan_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDeviceWireless_RequestScan_Call) RunAndReturn(run func() error) *MockDeviceWireless_RequestScan_Call {
	_c.Call.Return(run)
	return _c
}

// SetPropertyAutoConnect provides a mock function for the type MockDeviceWireless
func (_mock *MockDeviceWireless) SetPropertyAutoConnect(b bool) error {
	ret := _mock.Called(b)

	if len(ret) == 0 {
		panic("no return value specified for SetPropertyAutoConnect")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(bool) error); ok {
		r0 = returnFunc(b)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDeviceWireless_SetPropertyAutoConnect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetPropertyAutoConnect'
type MockDeviceWireless_SetPropertyAutoConnect_Call struct {
	*mock.Call
}

// SetPropertyAutoConnect is a helper method to define mock.On call
//   - b bool
func (_e *MockDeviceWireless_Expecter) SetPropertyAutoConnect(b any) *MockDeviceWireless_SetPropertyAutoConnect_Call {
	return &MockDeviceWireless_SetPropertyAutoConnect_Call{Call: _e.mock.On("SetPropertyAutoConnect", b)}
}

func (_c *MockDeviceWireless_SetPropertyAutoConnect_Call) Run(run func(b bool)) *MockDeviceWireless_SetPropertyAutoConnect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 bool
		if args[0] != nil {
			arg0 = args[0].(bool)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDeviceWireless_SetPropertyAutoConnect_Call) Return(err error) *MockDeviceWireless_SetPropertyAutoConnect_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDeviceWireless_SetPropertyAutoConnect_Call) RunAndReturn(run func(b bool) error) *MockDeviceWireless_SetPropertyAutoConnect_Call {
	_c.Call.Return(run)
	return _c
}

// SetPropertyManaged provides a mock function for the type MockDeviceWireless
func (_mock *MockDeviceWireless) SetPropertyManaged(b bool) error {
	ret := _mock.Called(b)

	if len(ret) == 0 {
		panic("no return value specified for SetPropertyManaged")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(bool) error); ok {
		r0 = returnFunc(b)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDeviceWireless_SetPropertyManaged_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetPropertyManaged'
type MockDeviceWireless_SetPropertyManaged_Call struct {
	*mock.Call
}

// SetPropertyManaged is a helper method to define mock.On call
//   - b bool
func (_e *MockDeviceWireless_Expecter) SetPropertyManaged(b any) *MockDeviceWireless_SetPropertyManaged_Call {
	return &MockDeviceWireless_SetPropertyManaged_Call{Call: _e.mock.On("SetPropertyManaged", b)}
}

func (_c *MockDeviceWireless_SetPropertyManaged_Call) Run(run func(b bool)) *MockDeviceWireless_SetPropertyManaged_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 bool
		if args[0] != nil {
			arg0 = args[0].(bool)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDeviceWireless_SetPropertyManaged_Call) Return(err error) *MockDeviceWireless_SetPropertyManaged_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDeviceWireless_SetPropertyManaged_Call) RunAndReturn(run func(b bool) error) *MockDeviceWireless_SetPropertyManaged_Call {
	_c.Call.Return(run)
	return _c
}

// SubscribeState provides a mock function for the type MockDeviceWireless
func (_mock *MockDeviceWireless) SubscribeState(receiver chan gonetworkmanager.DeviceStateChange, exit chan struct{}) error {
	ret := _mock.Called(receiver, exit)

	if len(ret) == 0 {
		panic("no return value specified for SubscribeState")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(chan gonetworkmanager.DeviceStateChange, chan struct{}) error); ok {
		r0 = returnFunc(receiver, exit)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDeviceWireless_SubscribeState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubscribeState'
type MockDeviceWireless_SubscribeState_Call struct {
	*mock.Call
}

// SubscribeState is a helper method to define mock.On call
//   - receiver chan gonetworkmanager.DeviceStateChange
//   - exit chan struct{}
func (_e *MockDeviceWireless_Expecter) SubscribeState(receiver any, exit any) *MockDeviceWireless_SubscribeState_Call {
	return &MockDeviceWireless_SubscribeState_Call{Call: _e.mock.On("SubscribeState", receiver, exit)}
}

func (_c *MockDeviceWireless_SubscribeState_Call) Run(run func(receiver chan gonetworkmanager.DeviceStateChange, exit chan struct{})) *MockDeviceWireless_SubscribeState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 chan gonetworkmanager.DeviceStateChange
		if args[0] != nil {
			arg0 = args[0].(chan gonetworkmanager.DeviceStateChange)
		}
		var arg1 chan struct{}
		if args[1] != nil {
			arg1 = args[1].(chan struct{})
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDeviceWireless_SubscribeState_Call) Return(err error) *MockDeviceWireless_SubscribeState_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDeviceWireless_SubscribeState_Call) RunAndReturn(run func(receiver chan gonetworkmanager.DeviceStateChange, exit chan struct{}) error) *MockDeviceWireless_SubscribeState_Call {
	_c.Call.Return(run)
	return _c
}
