-- Auto-generated by DMS — do not edit manually

hl.config({
	general = {
		gaps_in = 4,
		gaps_out = 4,
		border_size = 2,
	},
	decoration = {
		rounding = 12,
	},
	misc = {
		create_new_workspace = true,
	},
})

hl.config({ workspace = { id = 1, persistent = true } })
hl.config({ workspace = { id = 2, persistent = true } })
