// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks_evdev

import (
	"github.com/holoplot/go-evdev"
	mock "github.com/stretchr/testify/mock"
)

// NewMockEvdevDevice creates a new instance of MockEvdevDevice. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEvdevDevice(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEvdevDevice {
	mock := &MockEvdevDevice{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEvdevDevice is an autogenerated mock type for the EvdevDevice type
type MockEvdevDevice struct {
	mock.Mock
}

type MockEvdevDevice_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEvdevDevice) EXPECT() *MockEvdevDevice_Expecter {
	return &MockEvdevDevice_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockEvdevDevice
func (_mock *MockEvdevDevice) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEvdevDevice_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockEvdevDevice_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockEvdevDevice_Expecter) Close() *MockEvdevDevice_Close_Call {
	return &MockEvdevDevice_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockEvdevDevice_Close_Call) Run(run func()) *MockEvdevDevice_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEvdevDevice_Close_Call) Return(err error) *MockEvdevDevice_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEvdevDevice_Close_Call) RunAndReturn(run func() error) *MockEvdevDevice_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function for the type MockEvdevDevice
func (_mock *MockEvdevDevice) Name() (string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEvdevDevice_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockEvdevDevice_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockEvdevDevice_Expecter) Name() *MockEvdevDevice_Name_Call {
	return &MockEvdevDevice_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockEvdevDevice_Name_Call) Run(run func()) *MockEvdevDevice_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEvdevDevice_Name_Call) Return(s string, err error) *MockEvdevDevice_Name_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockEvdevDevice_Name_Call) RunAndReturn(run func() (string, error)) *MockEvdevDevice_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Path provides a mock function for the type MockEvdevDevice
func (_mock *MockEvdevDevice) Path() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Path")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockEvdevDevice_Path_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Path'
type MockEvdevDevice_Path_Call struct {
	*mock.Call
}

// Path is a helper method to define mock.On call
func (_e *MockEvdevDevice_Expecter) Path() *MockEvdevDevice_Path_Call {
	return &MockEvdevDevice_Path_Call{Call: _e.mock.On("Path")}
}

func (_c *MockEvdevDevice_Path_Call) Run(run func()) *MockEvdevDevice_Path_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEvdevDevice_Path_Call) Return(s string) *MockEvdevDevice_Path_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockEvdevDevice_Path_Call) RunAndReturn(run func() string) *MockEvdevDevice_Path_Call {
	_c.Call.Return(run)
	return _c
}

// ReadOne provides a mock function for the type MockEvdevDevice
func (_mock *MockEvdevDevice) ReadOne() (*evdev.InputEvent, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ReadOne")
	}

	var r0 *evdev.InputEvent
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*evdev.InputEvent, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *evdev.InputEvent); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*evdev.InputEvent)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEvdevDevice_ReadOne_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadOne'
type MockEvdevDevice_ReadOne_Call struct {
	*mock.Call
}

// ReadOne is a helper method to define mock.On call
func (_e *MockEvdevDevice_Expecter) ReadOne() *MockEvdevDevice_ReadOne_Call {
	return &MockEvdevDevice_ReadOne_Call{Call: _e.mock.On("ReadOne")}
}

func (_c *MockEvdevDevice_ReadOne_Call) Run(run func()) *MockEvdevDevice_ReadOne_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEvdevDevice_ReadOne_Call) Return(inputEvent *evdev.InputEvent, err error) *MockEvdevDevice_ReadOne_Call {
	_c.Call.Return(inputEvent, err)
	return _c
}

func (_c *MockEvdevDevice_ReadOne_Call) RunAndReturn(run func() (*evdev.InputEvent, error)) *MockEvdevDevice_ReadOne_Call {
	_c.Call.Return(run)
	return _c
}

// State provides a mock function for the type MockEvdevDevice
func (_mock *MockEvdevDevice) State(t evdev.EvType) (evdev.StateMap, error) {
	ret := _mock.Called(t)

	if len(ret) == 0 {
		panic("no return value specified for State")
	}

	var r0 evdev.StateMap
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(evdev.EvType) (evdev.StateMap, error)); ok {
		return returnFunc(t)
	}
	if returnFunc, ok := ret.Get(0).(func(evdev.EvType) evdev.StateMap); ok {
		r0 = returnFunc(t)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(evdev.StateMap)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(evdev.EvType) error); ok {
		r1 = returnFunc(t)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEvdevDevice_State_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'State'
type MockEvdevDevice_State_Call struct {
	*mock.Call
}

// State is a helper method to define mock.On call
//   - t evdev.EvType
func (_e *MockEvdevDevice_Expecter) State(t any) *MockEvdevDevice_State_Call {
	return &MockEvdevDevice_State_Call{Call: _e.mock.On("State", t)}
}

func (_c *MockEvdevDevice_State_Call) Run(run func(t evdev.EvType)) *MockEvdevDevice_State_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 evdev.EvType
		if args[0] != nil {
			arg0 = args[0].(evdev.EvType)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEvdevDevice_State_Call) Return(stateMap evdev.StateMap, err error) *MockEvdevDevice_State_Call {
	_c.Call.Return(stateMap, err)
	return _c
}

func (_c *MockEvdevDevice_State_Call) RunAndReturn(run func(t evdev.EvType) (evdev.StateMap, error)) *MockEvdevDevice_State_Call {
	_c.Call.Return(run)
	return _c
}
