// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks_utils

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockAppChecker creates a new instance of MockAppChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAppChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAppChecker {
	mock := &MockAppChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAppChecker is an autogenerated mock type for the AppChecker type
type MockAppChecker struct {
	mock.Mock
}

type MockAppChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAppChecker) EXPECT() *MockAppChecker_Expecter {
	return &MockAppChecker_Expecter{mock: &_m.Mock}
}

// AnyCommandExists provides a mock function for the type MockAppChecker
func (_mock *MockAppChecker) AnyCommandExists(cmds ...string) bool {
	// string
	_va := make([]any, len(cmds))
	for _i := range cmds {
		_va[_i] = cmds[_i]
	}
	var _ca []any
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for AnyCommandExists")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(...string) bool); ok {
		r0 = returnFunc(cmds...)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockAppChecker_AnyCommandExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AnyCommandExists'
type MockAppChecker_AnyCommandExists_Call struct {
	*mock.Call
}

// AnyCommandExists is a helper method to define mock.On call
//   - cmds ...string
func (_e *MockAppChecker_Expecter) AnyCommandExists(cmds ...any) *MockAppChecker_AnyCommandExists_Call {
	return &MockAppChecker_AnyCommandExists_Call{Call: _e.mock.On("AnyCommandExists",
		append([]any{}, cmds...)...)}
}

func (_c *MockAppChecker_AnyCommandExists_Call) Run(run func(cmds ...string)) *MockAppChecker_AnyCommandExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []string
		variadicArgs := make([]string, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *MockAppChecker_AnyCommandExists_Call) Return(b bool) *MockAppChecker_AnyCommandExists_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockAppChecker_AnyCommandExists_Call) RunAndReturn(run func(cmds ...string) bool) *MockAppChecker_AnyCommandExists_Call {
	_c.Call.Return(run)
	return _c
}

// AnyFlatpakExists provides a mock function for the type MockAppChecker
func (_mock *MockAppChecker) AnyFlatpakExists(flatpaks ...string) bool {
	// string
	_va := make([]any, len(flatpaks))
	for _i := range flatpaks {
		_va[_i] = flatpaks[_i]
	}
	var _ca []any
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for AnyFlatpakExists")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(...string) bool); ok {
		r0 = returnFunc(flatpaks...)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockAppChecker_AnyFlatpakExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AnyFlatpakExists'
type MockAppChecker_AnyFlatpakExists_Call struct {
	*mock.Call
}

// AnyFlatpakExists is a helper method to define mock.On call
//   - flatpaks ...string
func (_e *MockAppChecker_Expecter) AnyFlatpakExists(flatpaks ...any) *MockAppChecker_AnyFlatpakExists_Call {
	return &MockAppChecker_AnyFlatpakExists_Call{Call: _e.mock.On("AnyFlatpakExists",
		append([]any{}, flatpaks...)...)}
}

func (_c *MockAppChecker_AnyFlatpakExists_Call) Run(run func(flatpaks ...string)) *MockAppChecker_AnyFlatpakExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []string
		variadicArgs := make([]string, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *MockAppChecker_AnyFlatpakExists_Call) Return(b bool) *MockAppChecker_AnyFlatpakExists_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockAppChecker_AnyFlatpakExists_Call) RunAndReturn(run func(flatpaks ...string) bool) *MockAppChecker_AnyFlatpakExists_Call {
	_c.Call.Return(run)
	return _c
}

// CommandExists provides a mock function for the type MockAppChecker
func (_mock *MockAppChecker) CommandExists(cmd string) bool {
	ret := _mock.Called(cmd)

	if len(ret) == 0 {
		panic("no return value specified for CommandExists")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(cmd)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockAppChecker_CommandExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CommandExists'
type MockAppChecker_CommandExists_Call struct {
	*mock.Call
}

// CommandExists is a helper method to define mock.On call
//   - cmd string
func (_e *MockAppChecker_Expecter) CommandExists(cmd any) *MockAppChecker_CommandExists_Call {
	return &MockAppChecker_CommandExists_Call{Call: _e.mock.On("CommandExists", cmd)}
}

func (_c *MockAppChecker_CommandExists_Call) Run(run func(cmd string)) *MockAppChecker_CommandExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAppChecker_CommandExists_Call) Return(b bool) *MockAppChecker_CommandExists_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockAppChecker_CommandExists_Call) RunAndReturn(run func(cmd string) bool) *MockAppChecker_CommandExists_Call {
	_c.Call.Return(run)
	return _c
}

// FlatpakExists provides a mock function for the type MockAppChecker
func (_mock *MockAppChecker) FlatpakExists(name string) bool {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for FlatpakExists")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(name)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockAppChecker_FlatpakExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FlatpakExists'
type MockAppChecker_FlatpakExists_Call struct {
	*mock.Call
}

// FlatpakExists is a helper method to define mock.On call
//   - name string
func (_e *MockAppChecker_Expecter) FlatpakExists(name any) *MockAppChecker_FlatpakExists_Call {
	return &MockAppChecker_FlatpakExists_Call{Call: _e.mock.On("FlatpakExists", name)}
}

func (_c *MockAppChecker_FlatpakExists_Call) Run(run func(name string)) *MockAppChecker_FlatpakExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAppChecker_FlatpakExists_Call) Return(b bool) *MockAppChecker_FlatpakExists_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockAppChecker_FlatpakExists_Call) RunAndReturn(run func(name string) bool) *MockAppChecker_FlatpakExists_Call {
	_c.Call.Return(run)
	return _c
}
